force read from tty in case we are piped through curl

diff --git a/bin/bin/bootstrap b/bin/bin/bootstrap
--- a/bin/bin/bootstrap
+++ b/bin/bin/bootstrap
@@ -92,12 +92,12 @@ if ask "authorize public keys?" Y
 then
 	while [ -z "${github_user:-}" ]
 	do
-		read -p "github username: " github_user
+		read -p "github username: " github_user < /dev/tty
 	done
 	# download public keys from github
 	mkdir ~/.ssh 2>/dev/null || true
-	curl "https://github.com/$github_user.keys" >> ~/.ssh/authorized_keys \
-	|| error "downloading public keys failed"
+	curl "https://github.com/${github_user}.keys" # >> ~/.ssh/authorized_keys \
+	# || error "downloading public keys failed"
 fi
 
 while [ ! -f ~/.ssh/id_rsa.pub ]
