force read from tty in case we are piped through curl

diff --git a/bin/bin/bootstrap b/bin/bin/bootstrap
--- a/bin/bin/bootstrap
+++ b/bin/bin/bootstrap
@@ -96,8 +96,8 @@ then
 	done
 	# download public keys from github
 	mkdir ~/.ssh 2>/dev/null || true
-	curl "https://github.com/${github_user}.keys" # >> ~/.ssh/authorized_keys \
-	# || error "downloading public keys failed"
+	curl "https://github.com/${github_user}.keys" >> ~/.ssh/authorized_keys \
+	|| error "downloading public keys failed"
 fi
 
 while [ ! -f ~/.ssh/id_rsa.pub ]
