clean up the boostrap prompts

diff --git a/bin/bin/bootstrap b/bin/bin/bootstrap
--- a/bin/bin/bootstrap
+++ b/bin/bin/bootstrap
@@ -69,25 +69,26 @@ ask()
 
 trap cleanup EXIT
 
-info "first we can optionally update all currently installed packages via apt"
-if ask "update packages?" Y
+info "do you want to update all currently installed packages via apt?"
+info "(recommended)"
+if ask "?" Y
 then
 	# update installed packages
 	sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y && sudo apt-get autoremove -y
 fi
 
-info "we require some common utilities (git, make, stow) in order to install dotfiles"
-if ask "install utilities?" Y
+info "do you want to install git, make, and stow?"
+info "(required for installing dotfiles)"
+if ask "?" Y
 then
 	# install common utilities
 	(curl https://raw.githubusercontent.com/klutchell/dotfiles/master/bin/bin/myinstall | sudo bash -s git make stow \
 	|| error "some utilities failed to install")
 fi
 
-info "now we can optionally download your public github ssh keys and save them in ~/.ssh/authorized_keys"
-info "this will authorize your existing workstations to ssh into this server without a password"
-info "your github username will be required"
-if ask "authorize public keys?" Y
+info "do you want to download your public github ssh keys and save them in ~/.ssh/authorized_keys?"
+info "(allows your other workstations authenticate via keys to this workstation)"
+if ask "?" Y
 then
 	while [ -z "${github_user:-}" ]
 	do
@@ -102,8 +103,9 @@ fi
 while [ ! -f ~/.ssh/id_rsa.pub ]
 do
 	# generate id_rsa if it doesn't exist
-	info "the next few steps require a public ssh key saved in ~/.ssh/id_rsa.pub"
-	if ask "generate key?" Y
+	info "do you want to generate a public ssh key and save it in ~/.ssh/id_rsa.pub?"
+	info "(a public key will be required to authenticate with github)"
+	if ask "?" Y
 	then
 		ssh-keygen -f ~/.ssh/id_rsa -N '' -t rsa -b 4096 \
 		|| error "generating ssh-rsa key failed"
@@ -117,33 +119,33 @@ info "found public ssh key ~/.ssh/id_rsa.pub"
 key="$(cat ~/.ssh/id_rsa.pub)"
 title="${key##* }"
 
-info "in order to clone via ssh, we need to add your public ssh key for this workstation to your github account"
-info "your github username and password will be required"
-if ask "add public key?" Y
+info "do you want to add your public ssh key for this workstation to your github account?"
+info "(your github username and password will be required)"
+if ask "?" Y
 then
 	while [ -z "${github_user:-}" ]
 	do
 		read -p "github username: " github_user < /dev/tty
 	done
 	# upload public ssh key to github
-	curl --user "${github_user}" --data "{\"title\":\"${title}\",\"key\":\"${key}\"}" https://api.github.com/user/keys < /dev/tty \
-	|| fatal "uploading public key failed"
+	curl --user "${github_user}" --data "{\"title\":\"${title}\",\"key\":\"${key}\"}" \
+	https://api.github.com/user/keys < /dev/tty || fatal "uploading public key failed"
 fi
 
-info "now we can clone your dotfiles git repo into ~/dotfiles"
-if ask "clone repo?" Y
+info "do you want to clone your dotfiles git repo into ~/dotfiles?"
+info "(this is required to install dotfiles)"
+if ask "?" Y
 then
 	# clone dotfiles
 	git clone git@github.com:${github_user}/dotfiles.git ~/dotfiles \
 	|| fatal "cloning dotfiles repo failed"
-fi
 
-info "next we will use stow to soft link files and folders in ~/dotfiles/*/ to ~/"
-if ask "link dotfiles?" Y
-then
-	# install dotfiles
-	pushd ~/dotfiles
-	make install \
-	|| fatal "linking dotfiles failed"
-	popd
+	info "do you want to use stow to soft link files and folders in ~/dotfiles/*/ to ~/ ?"
+	if ask "?" Y
+	then
+		# install dotfiles
+		pushd ~/dotfiles
+		make install || fatal "linking dotfiles failed"
+		popd
+	fi
 fi
